tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "gh"
brew "git"
brew "node@16"
brew "mongosh"
brew "node"
brew "pipenv"
brew "postgresql@14", restart_service: true
brew "python@3.10"
brew "tree"
brew "heroku/brew/heroku"
